server:
  port: 6000


spring:
  application:
    name: GETWAY
  cloud:
    discovery: true
    gateway:
      routes:
        - id: LOGIN_SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**

        - id: ACCESS-MANAGEMENT
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/role/**

        - id: ACCESS-MANAGEMENT
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/userrole/**
     
        - id: ACCESS-MANAGEMENT
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/accessDash/**


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9000/eureka/

  instance:
    prefer-ip-address: true