server:
  port: 6000
spring:
  application:
    name: GETWAY
  config:
    import: "optional:configserver:http://localhost:8088"
  cloud:
    discovery: true
    gateway:
      routes:
        - id: LOGIN_SERVICE
          uri: lb://LOGIN-SERVICE
          predicates:
            - Path=/login/**

        - id: ACCESS-MANAGEMENT
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/role/**

        - id: ACCESS-MANAGEMENT
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/userrole/**

        - id: ACCESS-MANAGEMENT
          uri: lb://ACCESS-MANAGEMENT
          predicates:
            - Path=/accessDash/**