server:
  port: 8000
spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://192.168.0.30 :3306/rntdbuat
    username: rnt_app_user
    password: Random11Jun22
  application:
    name: LOGIN-SERVICE
  config:
    import: "optional:configserver:http://localhost:8088"